# Generated by Django 5.1.2 on 2026-05-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="NewsVerdict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("headline", models.TextField()),
                ("summary", models.TextField()),
                ("category", models.CharField(default="general", max_length=50)),
                ("source", models.CharField(max_length=255)),
                ("source_link", models.URLField()),
                (
                    "verdict",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("uncertain", "Uncertain"),
                            ("likely_fake", "Likely Fake"),
                        ],
                        max_length=20,
                    ),
                ),
                ("confidence_score", models.FloatField()),
                (
                    "confidence_level",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "red_flags",
                    models.JSONField(
                        default=list, help_text="List of detected red flags"
                    ),
                ),
                ("key_claim", models.TextField()),
                ("reason", models.TextField()),
                ("evidence_count", models.IntegerField(default=0)),
                ("evidence", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "news_verdicts",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="UserPreferences",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                (
                    "preferred_categories",
                    models.JSONField(
                        default=list, help_text="List of preferred news categories"
                    ),
                ),
                (
                    "filter_by_confidence",
                    models.CharField(
                        choices=[
                            ("all", "Show All"),
                            ("high", "High Confidence Only"),
                            ("medium_high", "Medium & High Confidence"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                (
                    "show_red_flags",
                    models.BooleanField(
                        default=True,
                        help_text="Show warnings for red flags (FIR, criminal records, etc.)",
                    ),
                ),
                (
                    "min_confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Minimum confidence score (0.0-1.0) to display news",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "user_preferences",
            },
        ),
    ]
